GENTES_CHOICES = [
    (1,'Acutia'),
    (2,'Aebutia'),
    (3,'Aelia'),
    (4,'Aemilia'),
    (5,'Albinia'),
    (6,'Aliena'),
    (7,'Anicia'),
    (8,'Annia'),
    (9,'Antia'),
    (10,'Antistia'),
    (11,'Antonia'),
    (12,'Appuleia'),
    (13,'Apronia'),
    (14,'Aquilia'),
    (15,'Aternia'),
    (16,'Atilia'),
    (17,'Atinia'),
    (18,'Aulia'),
    (19,'Caecilia'),
    (20,'Caedicia'),
    (21,'Calavia'),
    (22,'Canuleia'),
    (23,'Cassia'),
    (24,'Claudia'),
    (25,'Cloelia'),
    (26,'Cominia'),
    (27,'Cornelia'),
    (28,'Decia'),
    (29,'Domitia'),
    (30,'Duilia'),
    (31,'Fabia'),
    (32,'Flavia'),
    (33,'Foslia'),
    (34,'Fulcinia'),
    (35,'Fulvia'),
    (36,'Furia'),
    (37,'Furnia'),
    (38,'Gegania'),
    (39,'Genucia'),
    (40,'Herminia'),
    (41,'Horatia'),
    (42,'Hortensia'),
    (43,'Hostilia'),
    (44,'Icilia'),
    (45,'Iulia'),
    (46,'Iunia'),
    (47,'Iuventia'),
    (48,'Laceria'),
    (49,'Laetoria'),
    (50,'Lartia'),
    (51,'Lemonia'),
    (52,'Licinia'),
    (53,'Livia'),
    (54,'Lucretia'),
    (55,'Maecilia'),
    (56,'Maelia'),
    (57,'Maenia'),
    (58,'Mamilia'),
    (59,'Manilia'),
    (60,'Manlia'),
    (61,'Marcia'),
    (62,'Menenia'),
    (63,'Metilia'),
    (64,'Minucia'),
    (65,'Mucia'),
    (66,'Nautia'),
    (67,'Numicia'),
    (68,'Numisia'),
    (69,'Numitoria'),
    (70,'Ogulnia'),
    (71,'Oppia'),
    (72,'Papiria'),
    (73,'Petronia'),
    (74,'Pinaria'),
    (75,'Plautia'),
    (76,'Poetelia'),
    (77,'Pollia'),
    (78,'Pompilia'),
    (79,'Pomponia'),
    (80,'Pontia'),
    (81,'Popillia'),
    (82,'Postumia'),
    (83,'Potitia'),
    (84,'Publilia'),
    (85,'Pupia'),
    (86,'Quinctia'),
    (87,'Quinctilia'),
    (88,'Rabuleia'),
    (89,'Racilia'),
    (90,'Romilia'),
    (91,'Roscia'),
    (92,'Salonia'),
    (93,'Scaptia'),
    (94,'Seccia'),
    (95,'Sempronia'),
    (96,'Sergia'),
    (97,'Servilia'),
    (98,'Sestia'),
    (99,'Sextia'),
    (100,'Sextilia'),
    (101,'Sicinia'),
    (102,'Sulpicia'),
    (103,'Tarpeia'),
    (104,'Tarquinia'),
    (105,'Tarquitia'),
    (106,'Terentia'),
    (107,'Terentilia'),
    (108,'Tullia'),
    (109,'Valeria'),
    (110,'Verginia'),
    (111,'Veturia'),
    ]

PRAENOMINA_CHOICES = [
    (1,'Agrippina / Agrippa'),
    (2,'Appia / Appius'),
    (3,'Aula / Aulus'),
    (4,'Caesula / Caeso'),
    (5,'Decima / Decimus'),
    (6,'Fausta / Faustus'),
    (7,'Gaia / Gaius'),
    (8,'Gnaea / Gnaeus'),
    (9,'Hosta / Hostus'),
    (10,'Lucia / Lucius'),
    (11,'Mamaerca / Mamercus'),
    (12,'Mania / Manius'),
    (13,'Marcia / Marcus'),
    (14,'Mettia / Mettius'),
    (15,'Nona / Nonus'),
    (16,'Numeria / Numerius'),
    (17,'Octavia / Octavius'),
    (18,'Opita / Opiter'),
    (19,'Paulla / Paullus'),
    (20,'Postuma / Postumus'),
    (21,'Procula / Proculus'),
    (22,'Publia / Publius'),
    (23,'Quinta / Quintus'),
    (24,'Septima / Septimus'),
    (25,'Sertora / Sertor'),
    (26,'Servia / Servius'),
    (27,'Sexta / Sextus'),
    (28,'Spuria / Spurius'),
    (29,'Statia / Statius'),
    (30,'Tiberia / Tiberius'),
    (31,'Titia / Titus'),
    (32,'Tullia / Tullus'),
    (33,'Vibia / Vibius'),
    (34,'Volesa / Volesus'),
    (35,'Vopisca / Vopiscus'),
    ]

GENDER_CHOICES = [
        (1, 'Female'),
        (2, 'Male'),
        ]
